### ISSUE TITLE
@Cron annotations not working

### ISSUE THREAD

**Issue by npkumar** [jaumard/trailpack-cron#55]
I have `trailpack-annotations` and `trailpack-cron` `^2.0.0` installed
Adding a cron schedule via annotation does not work
```javascript
  /**
   * @Cron({schedule: '* * * * * *', start: true, timezone: 'Europe/Paris'})
   */
  testObj(){
    this.app.log.info('I am triggering every second from annotation!')
  }
```
I checked the value of `this.app.services.CronService.jobs` and find that schedules in`config/cron.js` is only present. Further checking shows that `@Cron` annotation is not recognized at all. Note that other `annotations` for eg `@Policy` works fine.
Any suggestions? Thanks!

**Comment by jaumard** [comment]
Hum you can try to run the test under this trailpack on your machine ? Looks like unit test are still green so maybe a configuration issue ? Did you add the cron.js file under index.js  ? Trailpack is correctly added under main.js file ?

**Comment by npkumar** [comment]
I noticed that in `config/annotations.js` path was set to `pathToScan: ['./api/controller']` by default. Changing to `./api` fixed the issue. Submitted #56 to add detail to README.md. Thanks!
